config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'welcome#index'
  resources :achievements

  namespace :api do
    resources :achievements, only: [:index]
  end
end

app/models/achievement.rb
# frozen_string_literal: true

class Achievement < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  # validates :title, uniqueness: true

  # validate :unique_title_for_one_user
  validates :title, uniqueness: {
    scope: :user_id,
    message: "you can't have two achievements with the same title"
  }

  validates :user, presence: true # already ?

  enum privacy: %i[public_access private_access friends_access]

  mount_uploader :cover_image, CoverImageUploader

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    # where('title LIKE ?', "#{letter}%")
    includes(:user).where('title LIKE ?', "#{letter}%").order('users.email')
  end

  # def unique_title_for_one_user
  #   existing_achievement = Achievement.find_by(title: title)
  #   if existing_achievement && existing_achievement.user == user
  #     errors.add(:title, "you can't have two achievements with the same title")
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/achievements_controller.rb
# frozen_string_literal: true

class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :owners_only, only: %i[edit update destroy]

  def index
    @achievements = Achievement.public_access
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def new
    @achievement = Achievement.new
  end

  def create
    @achievement = Achievement.new(**achievement_params, user: current_user)
    if @achievement.save
      UserMailer.achievement_created(current_user.email, @achievement.id).deliver_now
      tweet = TwitterService.new.tweet(@achievement.title)
      redirect_to achievement_url(@achievement), notice: "Achievement has been created. We tweeted for you! #{tweet.url}"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @achievement.update(achievement_params)
      redirect_to achievement_path(@achievement)
    else
      render :edit
    end
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    redirect_to achievements_path if current_user != @achievement.user
  end
end

app/controllers/api/achievements_controller.rb
module Api
  class AchievementsController < ApiController
    def index
      p request.headers["Content-Type"]

      achievements = Achievement.public_access
      render jsonapi: achievements
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :validate_header

  private

  def validate_header
    if request.headers["Content-Type"] != 'application/vnd.api+json'
      render json: {}, status: 400
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/achievements/new.html.erb
<%= form_with model: @achievement, local: true do |f| %>


  <% if @achievement.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@achievement.errors.count, "error") %> prohibited
        this achievement from being saved:
      </h2>
      <ul>
        <% @achievement.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.label :privacy %>
  <%= f.select :privacy, Achievement.privacies.map { |k, v| [k.split('_').first.capitalize, k] }.to_h %>
</p>

<p>
  <%= f.label :featured, "Featured achievement" %>
  <%= f.check_box :featured %>
</p>

<p>
  <%= f.label :cover_image %>
  <%= f.file_field :cover_image %>
</p>

<p>
  <%= f.submit class: 'btn btn-primary' %>
</p>

<% end %>

app/views/achievements/show.html.erb
<h1><%= @achievement.title %></h1>
<div>
  <%= @achievement.description_html.html_safe %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IRock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">I Rock</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="#">Home <span class="sr-only">(current)</span></a>
            <%= link_to 'New Achievement', new_achievement_path %></li>
            <a class="nav-item nav-link" href="#">Features</a>
            <a class="nav-item nav-link" href="#">Pricing</a>
            <a class="nav-item nav-link disabled" href="#">Disabled</a>
          </div>
        </div>
      </nav>

<% if  flash[:notice] %>
<div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>